baseURL = "https://www.example.com"
languageCode = "en-us"
removePathAccents = true
theme = "infinity-hugo"
title = "Infinity | Comming Soon Hugo Template By Themefisher"
[params]
customHead = ""
[params.about]
description = "«Ocean : Inspire» is the brainchild of Leonardo Zangrando, who created it to fulfil his mission to inspire 100 million people take individual and collective action for Ocean Sustainability. Leonardo's deep love for the Ocean starts back in his childhood and he has been swimming, diving, sailing since then. He realised that people feel powerless when facing such a giant challenge like protecting, preserving and restoring the Ocean. Leonardo wants to inspire people to realise that they can take individual action, that their action counts, and that they can multiply their impact 100-fold if they want and know how to. «Ocean : Inspire» is there to create Events, Talks, Documentaries to inspire people take actual action after inspiration."
enable = true
heading = "«Ocean : Inspire» – Events, Talks, Documentaries to Inspire People to TAKE ACTION!"
[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[params.contact]
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"
title = "Get In Touch"
[params.cta]
bg = "images/call-to-action.jpg"
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
title = "Subscribe to our mailing list"
[params.hero]
bg = "images/header-bg.jpg"
btnText = "Get Started"
countdownDay = "31"
countdownMonth = "12"
countdownYear = "2021"
disableCountdown = true
enable = true
subtitle = "Inspiring 100 Million People to Take Individual and Collective Action for Ocean Sustainability"
title = "«Ocean : Inspire»"
[params.navigation]
about = "About"
contact = "Contact"
home = "Home"
logo = "images/logo.png"
service = "Services"
[params.service]
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"
title = "Find Better Solutions Build Better Products"
[[params.service.serviceItem]]
delay = "0s"
description = "Creating and delivering Talks to inspire people take individual and collective action for Ocean Sustainability."
icon = "tf-strategy"
title = "Talks"
[[params.service.serviceItem]]
delay = "0.2s"
description = "Creating and delivering Workshops to inspire people take individual and collective action for Ocean Sustainability."
icon = "tf-circle-compass"
title = "Workshops"
[[params.service.serviceItem]]
delay = "0.4s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-anchor2"
title = "Tons of Feature"
[[params.service.serviceItem]]
delay = "0.6s"
description = "Producing Documentaries to inspire people take action for Ocean Sustainability."
icon = "tf-globe"
title = "Documentaries"
